### ISSUE TITLE
Looking for your SVG code!

### ISSUE THREAD

**Issue by gtoal** [silasfiore/avl-python#1]
Apologies for posting in an unrelated project, but you're a hard man to find and this is the only way I've worked out that I might be able to contact you with.

Some time ago you had a project here 'https://github.com/silasfiore/svg_cnc' which (according to my old bookmark) was code to reconstitute a Bezier curve from an SVG where the curve had been flattened to approximately equivalent straight-line segments.

Since this seems to be the *only* code anywhere that I've found which does this, and since I'm working on the same problem myself, I was hoping to have a look at it and see if you have any good ideas in it that I might have missed.  I do have a working solution but it's not perfect - there are some issues with cusps and sharp corners that could be improved.

Regards,
Graham Toal <gtoal@gtoal.com>
![logobez](https://user-images.githubusercontent.com/8899318/223569103-a92266c5-4b8e-45c6-8bc8-d5065e622ca7.png)

**Comment by silasfiore** [comment]
Hi,
I think you are referring to the code I wrote to interpolate airfoil
coordinates and to print them to an SVG path. You can find it here:
https://github.com/silasfiore/dat2svg
If you have a set of ordered points (i.e. line segments that approximate a
smooth shape) the fitcubics function can be used to interpolate them with a
C2 continuous composite bezier curve.
Hope this helps.
Cheers,
Silas

Graham Toal ***@***.***> schrieb am Di., 7. März 2023, 23:34:

**Comment by gtoal** [comment]
That's what I was looking for, thanks!
